### ISSUE TITLE
Google Analytics 4 properties

### ISSUE THREAD

**Issue by Inklud** [nuxt-community/gooogle-analytics-module#95]
The new Google Analytics 4 properties seems not to be supported by gooogle-analytics-module.

The new Google Analytics tracking Id looks like this: G-XXXXXXX

When trying to add it i get the following error:
"analytics_debug.js:25 The tracking Id should only be of the format UA-NNNNNN-N."

How can we fix this?

**Comment by MatteoGabriele** [comment]
You need to switch to a module that supports gtag.js
You can read more here https://github.com/nuxt-community/gtm-module/issues/82

**Comment by Inklud** [comment]
Thank you.
